version: 0.0
os: linux
files:
  - source: /
    destination: /data/dis
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: npm install
      timeout: 1200
      runas: ec2-user
    - location: npm install forever
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: /node_modules/forever/bin/forever /app.js
      timeout: 1200
      runas:  ec2-user
