version: 0.0
os: linux
files:
  - source: /
    destination: /data/dis
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 1200
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start-app.sh
      timeout: 300
      runas:  ec2-user
  ApplicationStop:
    - location: scripts/stop-app.sh
      timeout: 300
      runas: ec2-user
