version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo 'Starting build.'
      - npm --no-git-tag-version version patch
      - PACKAGE_VERSION=$(scripts/get-package-version.sh)
      - echo "$PACKAGE_VERSION"
      - git tag -a "${PACKAGE_VERSION}" -m  "Version ${PACKAGE_VERSION}"
      - git push origin --tags
  build:
    commands:
      - npm install
  post_build:
    commands:
      - echo 'Build done.'
artifacts:
  discard-paths: no
  files:
    - package.json
    - package-lock.json
    - appsspec.yml
    - app.js
    - bin/**/*
    - public/**/*
    - routes/**/*
    - scripts/**/*
    - node_modules/**/*

