version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo 'Starting build.'
      - npm version patch
      - scripts/get-package-version.sh
      - export PACKAGE_VERSION="v${version}"
      - git tag -a "${PACKAGE_VERSION}"
      - git push origin --tags
      - echo "$PACKAGE_VERSION"
  build:
    commands:
      - npm install
  post_build:
    commands:
      - echo 'Build done.'
artifacts:
  discard-paths: no
  files:
    - package.json
    - package-lock.json
    - appsspec.yml
    - app.js
    - bin/**/*
    - public/**/*
    - routes/**/*
    - scripts/**/*
    - node_modules/**/*

